/* Generated by tools/make_pixel_font.py from the FireRed font recreation. Do not edit. */
#pragma once

#include "lvgl.h"

#define PIXEL_FONT_HEIGHT 36

/* Glyph sprite (NULL for space/unknown) and its horizontal advance. */
const lv_image_dsc_t *pixel_font_glyph(char c);
int32_t pixel_font_advance(char c);

