/* Generated by tools/make_pixel_font.py. Do not edit. */
#pragma once

#include "lvgl.h"

#define PIXEL_FONT_HEIGHT 21
#define PIXEL_FONT_GLYPH_SCALE 3

/* 5x7 glyph sprite (NULL for space/unknown; case-insensitive) and advance. */
const lv_image_dsc_t *pixel_font_glyph(char c);
int32_t pixel_font_advance(char c);

