/* Generated by tools/make_pixel_font.py. Do not edit. */
#pragma once

#include "lvgl.h"

/* 5x7 pixel glyph at scene scale, or NULL for unknown characters. */
const lv_image_dsc_t *pixel_font_glyph(char c);

