/* Generated by tools/convert_sprites.py from raichu PMD sheets. Do not edit. */
#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t *const raichu_idle_frames[];
extern const uint32_t raichu_idle_durations_ms[];
extern const uint32_t raichu_idle_frame_count;

extern const lv_image_dsc_t *const raichu_sit_frames[];
extern const uint32_t raichu_sit_durations_ms[];
extern const uint32_t raichu_sit_frame_count;

extern const lv_image_dsc_t *const raichu_nod_frames[];
extern const uint32_t raichu_nod_durations_ms[];
extern const uint32_t raichu_nod_frame_count;

extern const lv_image_dsc_t *const raichu_pose_frames[];
extern const uint32_t raichu_pose_durations_ms[];
extern const uint32_t raichu_pose_frame_count;

extern const lv_image_dsc_t *const raichu_shock_frames[];
extern const uint32_t raichu_shock_durations_ms[];
extern const uint32_t raichu_shock_frame_count;

extern const lv_image_dsc_t *const raichu_hop_frames[];
extern const uint32_t raichu_hop_durations_ms[];
extern const uint32_t raichu_hop_frame_count;

extern const lv_image_dsc_t *const raichu_breath_frames[];
extern const uint32_t raichu_breath_durations_ms[];
extern const uint32_t raichu_breath_frame_count;

extern const lv_image_dsc_t *const raichu_walk_s_frames[];
extern const uint32_t raichu_walk_s_durations_ms[];
extern const uint32_t raichu_walk_s_frame_count;

extern const lv_image_dsc_t *const raichu_walk_se_frames[];
extern const uint32_t raichu_walk_se_durations_ms[];
extern const uint32_t raichu_walk_se_frame_count;

extern const lv_image_dsc_t *const raichu_walk_e_frames[];
extern const uint32_t raichu_walk_e_durations_ms[];
extern const uint32_t raichu_walk_e_frame_count;

extern const lv_image_dsc_t *const raichu_walk_ne_frames[];
extern const uint32_t raichu_walk_ne_durations_ms[];
extern const uint32_t raichu_walk_ne_frame_count;

extern const lv_image_dsc_t *const raichu_walk_n_frames[];
extern const uint32_t raichu_walk_n_durations_ms[];
extern const uint32_t raichu_walk_n_frame_count;

extern const lv_image_dsc_t *const raichu_walk_nw_frames[];
extern const uint32_t raichu_walk_nw_durations_ms[];
extern const uint32_t raichu_walk_nw_frame_count;

extern const lv_image_dsc_t *const raichu_walk_w_frames[];
extern const uint32_t raichu_walk_w_durations_ms[];
extern const uint32_t raichu_walk_w_frame_count;

extern const lv_image_dsc_t *const raichu_walk_sw_frames[];
extern const uint32_t raichu_walk_sw_durations_ms[];
extern const uint32_t raichu_walk_sw_frame_count;

