/* Generated by tools/convert_sprites.py from raichu PMD sheets. Do not edit. */
#pragma once

#include "lvgl.h"

extern const lv_image_dsc_t *const raichu_idle_frames[];
extern const uint32_t raichu_idle_durations_ms[];
extern const uint32_t raichu_idle_frame_count;

extern const lv_image_dsc_t *const raichu_walk_east_frames[];
extern const uint32_t raichu_walk_east_durations_ms[];
extern const uint32_t raichu_walk_east_frame_count;

extern const lv_image_dsc_t *const raichu_walk_west_frames[];
extern const uint32_t raichu_walk_west_durations_ms[];
extern const uint32_t raichu_walk_west_frame_count;

