#!/usr/bin/env python3
"""
Converts PMD SpriteCollab sheets into LVGL ARGB8888 C arrays.

Takes the south-facing (camera-facing) row of each animation sheet, upscales
it with nearest-neighbor so the pixel art stays crisp under LVGL's bilinear
transforms, and emits one .c/.h pair with frame descriptors + durations.

Usage: python3 tools/convert_sprites.py assets/raichu app/sprites raichu
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from PIL import Image

# Sheet rows are the 8 facing directions: 0=S, 1=SE, 2=E, 3=NE, 4=N, 5=NW, 6=W, 7=SW.
DIRECTIONS = ["s", "se", "e", "ne", "n", "nw", "w", "sw"]
ANIMS = [
    {"anim": "Idle", "row": 0, "name": "idle"},
    {"anim": "Sit", "row": 0, "name": "sit"},
] + [
    {"anim": "Walk", "row": row, "name": f"walk_{direction}"}
    for row, direction in enumerate(DIRECTIONS)
]
TICK_MS = 1000 / 60  # AnimData durations are 60fps game ticks

# Transparent padding is cropped away first, then the largest integer scale
# that fits every animation into this box is used, capped so the pet reads as
# a large character rather than wall-to-wall (13x uncapped felt too big).
TARGET_WIDTH = 386
TARGET_HEIGHT = 446
SCALE_CAP = 6


def load_anim_meta(sprite_dir: Path, name: str) -> dict:
    root = ET.parse(sprite_dir / "AnimData.xml").getroot()
    for anim in root.iter("Anim"):
        if anim.findtext("Name") == name:
            return {
                "frame_width": int(anim.findtext("FrameWidth")),
                "frame_height": int(anim.findtext("FrameHeight")),
                "durations": [int(d.text) for d in anim.iter("Duration")],
            }
    raise SystemExit(f"animation {name} not found in AnimData.xml")


def row_frames(sheet: Image.Image, frame_width: int, frame_height: int, row: int) -> list:
    frames = []
    top = row * frame_height
    for index in range(sheet.width // frame_width):
        frame = sheet.crop((index * frame_width, top, (index + 1) * frame_width, top + frame_height))
        frames.append(frame.convert("RGBA"))
    return frames


def union_alpha_bbox(frames: list) -> tuple:
    """Smallest box containing every frame's visible pixels, so cropping never clips a pose."""
    left, top, right, bottom = frames[0].getchannel("A").getbbox()
    for frame in frames[1:]:
        box = frame.getchannel("A").getbbox()
        left, top = min(left, box[0]), min(top, box[1])
        right, bottom = max(right, box[2]), max(bottom, box[3])
    return left, top, right, bottom


def fit_scale(content_width: int, content_height: int) -> int:
    return min(TARGET_WIDTH // content_width, TARGET_HEIGHT // content_height, SCALE_CAP)


def frame_to_argb8888_bytes(frame: Image.Image) -> bytes:
    rgba = frame.convert("RGBA").tobytes()
    bgra = bytearray(len(rgba))
    bgra[0::4] = rgba[2::4]
    bgra[1::4] = rgba[1::4]
    bgra[2::4] = rgba[0::4]
    bgra[3::4] = rgba[3::4]
    return bytes(bgra)


def emit_frame(c_out: list, symbol: str, frame: Image.Image) -> None:
    data = frame_to_argb8888_bytes(frame)
    c_out.append(f"static const uint8_t {symbol}_map[] = {{")
    for offset in range(0, len(data), 24):
        chunk = ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 24])
        c_out.append(f"    {chunk},")
    c_out.append("};")
    c_out.append(f"static const lv_image_dsc_t {symbol} = {{")
    c_out.append("    .header.magic = LV_IMAGE_HEADER_MAGIC,")
    c_out.append("    .header.cf = LV_COLOR_FORMAT_ARGB8888,")
    c_out.append(f"    .header.w = {frame.width},")
    c_out.append(f"    .header.h = {frame.height},")
    c_out.append(f"    .header.stride = {frame.width * 4},")
    c_out.append(f"    .data_size = sizeof({symbol}_map),")
    c_out.append(f"    .data = {symbol}_map,")
    c_out.append("};")


def main() -> None:
    sprite_dir, out_dir, prefix = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
    out_dir.mkdir(parents=True, exist_ok=True)

    c_out = [
        f"/* Generated by tools/convert_sprites.py from {sprite_dir.name} PMD sheets. Do not edit. */",
        '#include "lvgl.h"',
        f'#include "{prefix}_sprites.h"',
        "",
    ]
    h_out = [
        f"/* Generated by tools/convert_sprites.py from {sprite_dir.name} PMD sheets. Do not edit. */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
    ]

    anims = []
    for spec in ANIMS:
        meta = load_anim_meta(sprite_dir, spec["anim"])
        sheet = Image.open(sprite_dir / f"{spec['anim']}-Anim.png")
        frames = row_frames(sheet, meta["frame_width"], meta["frame_height"], spec["row"])
        bbox = union_alpha_bbox(frames)
        anims.append({"name": spec["name"], "meta": meta, "frames": frames, "bbox": bbox})

    # One scale for every animation so the pet doesn't change size between states.
    scale = min(
        fit_scale(anim["bbox"][2] - anim["bbox"][0], anim["bbox"][3] - anim["bbox"][1])
        for anim in anims
    )

    for anim in anims:
        lower = anim["name"].lower()
        left, top, right, bottom = anim["bbox"]
        frames = [
            frame.crop(anim["bbox"]).resize(
                ((right - left) * scale, (bottom - top) * scale), Image.NEAREST
            )
            for frame in anim["frames"]
        ]
        meta = anim["meta"]

        for index, frame in enumerate(frames):
            emit_frame(c_out, f"{prefix}_{lower}_{index}", frame)

        frame_refs = ", ".join(f"&{prefix}_{lower}_{index}" for index in range(len(frames)))
        durations = ", ".join(str(round(ticks * TICK_MS)) for ticks in meta["durations"])
        c_out.append(f"const lv_image_dsc_t *const {prefix}_{lower}_frames[] = {{{frame_refs}}};")
        c_out.append(f"const uint32_t {prefix}_{lower}_durations_ms[] = {{{durations}}};")
        c_out.append(f"const uint32_t {prefix}_{lower}_frame_count = {len(frames)};")
        c_out.append("")

        h_out.append(f"extern const lv_image_dsc_t *const {prefix}_{lower}_frames[];")
        h_out.append(f"extern const uint32_t {prefix}_{lower}_durations_ms[];")
        h_out.append(f"extern const uint32_t {prefix}_{lower}_frame_count;")
        h_out.append("")

        print(f"{anim['name']}: {len(frames)} frames {frames[0].width}x{frames[0].height} (scale {scale}x)")

    (out_dir / f"{prefix}_sprites.c").write_text("\n".join(c_out) + "\n")
    (out_dir / f"{prefix}_sprites.h").write_text("\n".join(h_out) + "\n")


if __name__ == "__main__":
    main()
