#!/usr/bin/env python3
"""
Generates the HUD chrome as pixel art at the scene's 6px scale:
the dialog box frame and the EXP bar frame (app/sprites/hud_box.c/.h).
Drawn at logical resolution (no anti-aliasing) then nearest-upscaled,
so corners are stepped like GBA dialog boxes.

Usage: python3 tools/make_hud.py app/sprites
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).parent))
from convert_sprites import emit_frame

PIXEL_SIZE = 6

BOX_UNITS = (60, 16)   # 360 x 96 on screen (inset for the rounded panel)
BAR_UNITS = (54, 4)    # 324 x 24 on screen

FILL = (248, 248, 232, 255)
BORDER = (88, 80, 72, 255)
SLOT = (80, 72, 64, 255)


def pixel_rounded_rect(size: tuple, radius: int, fill: tuple, outline: tuple) -> Image.Image:
    image = Image.new("RGBA", size)
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle([0, 0, size[0] - 1, size[1] - 1],
                           radius=radius, fill=fill, outline=outline, width=1)
    return image  # native logical pixels; runtime scales by HUD_SCALE


def main() -> None:
    out_dir = Path(sys.argv[1])

    c_out = [
        "/* Generated by tools/make_hud.py. Do not edit. */",
        '#include "lvgl.h"',
        '#include "hud_box.h"',
        "",
    ]
    emit_frame(c_out, "hud_dialog_box_image", pixel_rounded_rect(BOX_UNITS, 3, FILL, BORDER))
    emit_frame(c_out, "hud_exp_frame_image", pixel_rounded_rect(BAR_UNITS, 1, SLOT, BORDER))
    c_out.append("const lv_image_dsc_t *const hud_dialog_box = &hud_dialog_box_image;")
    c_out.append("const lv_image_dsc_t *const hud_exp_frame = &hud_exp_frame_image;")
    c_out.append("")

    h_out = [
        "/* Generated by tools/make_hud.py. Do not edit. */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
        f"#define HUD_SCALE {PIXEL_SIZE}",
        "",
        "extern const lv_image_dsc_t *const hud_dialog_box;",
        "extern const lv_image_dsc_t *const hud_exp_frame;",
        "",
    ]

    (out_dir / "hud_box.c").write_text("\n".join(c_out) + "\n")
    (out_dir / "hud_box.h").write_text("\n".join(h_out) + "\n")
    print("hud chrome generated")


if __name__ == "__main__":
    main()
