#!/usr/bin/env python3
"""
Generates the HUD font from the FireRed font recreation TTF as LVGL glyph
sprites (app/sprites/pixel_font.c/.h). Rendered at the font's native pixel
grid with anti-aliasing off, then nearest-upscaled; advances are
proportional, straight from the font metrics.

Usage: python3 tools/make_pixel_font.py app/sprites
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, str(Path(__file__).parent))
from convert_sprites import emit_frame

FONT_PATH = Path(__file__).parent.parent / "assets/fonts/pokemon_fire_red.ttf"
FONT_SIZE = 16  # the recreation's native pixel grid — other sizes distort
PIXEL_SIZE = 3
INK = (56, 48, 48, 255)

CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789:./!?+-'"


def main() -> None:
    out_dir = Path(sys.argv[1])
    font = ImageFont.truetype(str(FONT_PATH), FONT_SIZE)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    canvases = {}
    advances = {}
    ink_top, ink_bottom = line_height, 0
    for char in CHARS:
        advance = round(font.getlength(char))
        width = max(advance, font.getbbox(char)[2], 1)
        canvas = Image.new("RGBA", (width, line_height))
        draw = ImageDraw.Draw(canvas)
        draw.fontmode = "1"
        draw.text((0, 0), char, font=font, fill=INK)
        bbox = canvas.getchannel("A").getbbox()
        if bbox is not None:
            ink_top = min(ink_top, bbox[1])
            ink_bottom = max(ink_bottom, bbox[3])
        canvases[char] = canvas
        advances[char] = advance
    advances[" "] = round(font.getlength(" "))

    c_out = [
        "/* Generated by tools/make_pixel_font.py from the FireRed font recreation. Do not edit. */",
        '#include "lvgl.h"',
        '#include "pixel_font.h"',
        "",
    ]
    names = {}
    for char, canvas in canvases.items():
        # Shared vertical crop keeps every glyph on the same baseline.
        cropped = canvas.crop((0, ink_top, canvas.width, ink_bottom))
        scaled = cropped.resize(
            (cropped.width * PIXEL_SIZE, cropped.height * PIXEL_SIZE), Image.NEAREST
        )
        name = f"pixel_font_{ord(char)}"
        names[char] = name
        emit_frame(c_out, name, scaled)

    c_out.append("const lv_image_dsc_t *pixel_font_glyph(char c)")
    c_out.append("{")
    c_out.append("    switch (c) {")
    for char, name in sorted(names.items()):
        escaped = "\\'" if char == "'" else char
        c_out.append(f"    case '{escaped}': return &{name};")
    c_out.append("    default: return NULL;")
    c_out.append("    }")
    c_out.append("}")
    c_out.append("")
    c_out.append("int32_t pixel_font_advance(char c)")
    c_out.append("{")
    c_out.append("    switch (c) {")
    for char, advance in sorted(advances.items()):
        escaped = "\\'" if char == "'" else char
        c_out.append(f"    case '{escaped}': return {advance * PIXEL_SIZE};")
    c_out.append("    default: return 0;")
    c_out.append("    }")
    c_out.append("}")
    c_out.append("")

    height = (ink_bottom - ink_top) * PIXEL_SIZE
    h_out = [
        "/* Generated by tools/make_pixel_font.py from the FireRed font recreation. Do not edit. */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
        f"#define PIXEL_FONT_HEIGHT {height}",
        "",
        "/* Glyph sprite (NULL for space/unknown) and its horizontal advance. */",
        "const lv_image_dsc_t *pixel_font_glyph(char c);",
        "int32_t pixel_font_advance(char c);",
        "",
    ]

    (out_dir / "pixel_font.c").write_text("\n".join(c_out) + "\n")
    (out_dir / "pixel_font.h").write_text("\n".join(h_out) + "\n")
    print(f"{len(names)} glyphs, height {height}px")


if __name__ == "__main__":
    main()
