#!/usr/bin/env python3
"""
Generates the HUD's 5x7 pixel font as LVGL glyph images at the scene's
6px-per-pixel scale (app/sprites/pixel_font.c/.h).

Usage: python3 tools/make_pixel_font.py app/sprites
"""
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).parent))
from convert_sprites import emit_frame

PIXEL_SIZE = 4
INK = (56, 48, 48, 255)

# 5 columns x 7 rows, 'X' = ink. Covers the HUD's needs: A-Z 0-9 : . /
GLYPHS = {
    "0": [".XXX.", "X...X", "X..XX", "X.X.X", "XX..X", "X...X", ".XXX."],
    "1": ["..X..", ".XX..", "..X..", "..X..", "..X..", "..X..", ".XXX."],
    "2": [".XXX.", "X...X", "....X", "...X.", "..X..", ".X...", "XXXXX"],
    "3": [".XXX.", "X...X", "....X", "..XX.", "....X", "X...X", ".XXX."],
    "4": ["...X.", "..XX.", ".X.X.", "X..X.", "XXXXX", "...X.", "...X."],
    "5": ["XXXXX", "X....", "XXXX.", "....X", "....X", "X...X", ".XXX."],
    "6": ["..XX.", ".X...", "X....", "XXXX.", "X...X", "X...X", ".XXX."],
    "7": ["XXXXX", "....X", "...X.", "..X..", ".X...", ".X...", ".X..."],
    "8": [".XXX.", "X...X", "X...X", ".XXX.", "X...X", "X...X", ".XXX."],
    "9": [".XXX.", "X...X", "X...X", ".XXXX", "....X", "...X.", ".XX.."],
    "A": [".XXX.", "X...X", "X...X", "XXXXX", "X...X", "X...X", "X...X"],
    "B": ["XXXX.", "X...X", "X...X", "XXXX.", "X...X", "X...X", "XXXX."],
    "C": [".XXX.", "X...X", "X....", "X....", "X....", "X...X", ".XXX."],
    "D": ["XXXX.", "X...X", "X...X", "X...X", "X...X", "X...X", "XXXX."],
    "E": ["XXXXX", "X....", "X....", "XXXX.", "X....", "X....", "XXXXX"],
    "F": ["XXXXX", "X....", "X....", "XXXX.", "X....", "X....", "X...."],
    "G": [".XXX.", "X...X", "X....", "X.XXX", "X...X", "X...X", ".XXXX"],
    "H": ["X...X", "X...X", "X...X", "XXXXX", "X...X", "X...X", "X...X"],
    "I": [".XXX.", "..X..", "..X..", "..X..", "..X..", "..X..", ".XXX."],
    "J": ["..XXX", "...X.", "...X.", "...X.", "...X.", "X..X.", ".XX.."],
    "K": ["X...X", "X..X.", "X.X..", "XX...", "X.X..", "X..X.", "X...X"],
    "L": ["X....", "X....", "X....", "X....", "X....", "X....", "XXXXX"],
    "M": ["X...X", "XX.XX", "X.X.X", "X.X.X", "X...X", "X...X", "X...X"],
    "N": ["X...X", "XX..X", "X.X.X", "X..XX", "X...X", "X...X", "X...X"],
    "O": [".XXX.", "X...X", "X...X", "X...X", "X...X", "X...X", ".XXX."],
    "P": ["XXXX.", "X...X", "X...X", "XXXX.", "X....", "X....", "X...."],
    "Q": [".XXX.", "X...X", "X...X", "X...X", "X.X.X", "X..X.", ".XX.X"],
    "R": ["XXXX.", "X...X", "X...X", "XXXX.", "X.X..", "X..X.", "X...X"],
    "S": [".XXXX", "X....", "X....", ".XXX.", "....X", "....X", "XXXX."],
    "T": ["XXXXX", "..X..", "..X..", "..X..", "..X..", "..X..", "..X.."],
    "U": ["X...X", "X...X", "X...X", "X...X", "X...X", "X...X", ".XXX."],
    "V": ["X...X", "X...X", "X...X", "X...X", "X...X", ".X.X.", "..X.."],
    "W": ["X...X", "X...X", "X...X", "X.X.X", "X.X.X", "XX.XX", "X...X"],
    "X": ["X...X", "X...X", ".X.X.", "..X..", ".X.X.", "X...X", "X...X"],
    "Y": ["X...X", "X...X", ".X.X.", "..X..", "..X..", "..X..", "..X.."],
    "Z": ["XXXXX", "....X", "...X.", "..X..", ".X...", "X....", "XXXXX"],
    ":": [".....", "..X..", "..X..", ".....", "..X..", "..X..", "....."],
    ".": [".....", ".....", ".....", ".....", ".....", "..X..", "..X.."],
    "/": ["....X", "...X.", "...X.", "..X..", ".X...", ".X...", "X...."],
}


def glyph_image(rows: list) -> Image.Image:
    image = Image.new("RGBA", (5, 7))
    pixels = image.load()
    for y, row in enumerate(rows):
        for x, cell in enumerate(row):
            if cell == "X":
                pixels[x, y] = INK
    return image.resize((5 * PIXEL_SIZE, 7 * PIXEL_SIZE), Image.NEAREST)


def main() -> None:
    out_dir = Path(sys.argv[1])

    c_out = [
        "/* Generated by tools/make_pixel_font.py. Do not edit. */",
        '#include "lvgl.h"',
        '#include "pixel_font.h"',
        "",
    ]
    names = {}
    for char, rows in GLYPHS.items():
        name = f"pixel_font_{ord(char)}"
        names[char] = name
        emit_frame(c_out, name, glyph_image(rows))

    c_out.append("const lv_image_dsc_t *pixel_font_glyph(char c)")
    c_out.append("{")
    c_out.append("    switch (c) {")
    for char, name in sorted(names.items()):
        if char.isalpha():
            c_out.append(f"    case '{char}': case '{char.lower()}': return &{name};")
        else:
            c_out.append(f"    case '{char}': return &{name};")
    c_out.append("    default: return NULL;")
    c_out.append("    }")
    c_out.append("}")
    c_out.append("")
    c_out.append("int32_t pixel_font_advance(char c)")
    c_out.append("{")
    c_out.append("    LV_UNUSED(c);")
    c_out.append(f"    return {6 * PIXEL_SIZE};")
    c_out.append("}")
    c_out.append("")

    h_out = [
        "/* Generated by tools/make_pixel_font.py. Do not edit. */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
        f"#define PIXEL_FONT_HEIGHT {7 * PIXEL_SIZE}",
        "",
        "/* 5x7 glyph sprite (NULL for space/unknown; case-insensitive) and advance. */",
        "const lv_image_dsc_t *pixel_font_glyph(char c);",
        "int32_t pixel_font_advance(char c);",
        "",
    ]

    (out_dir / "pixel_font.c").write_text("\n".join(c_out) + "\n")
    (out_dir / "pixel_font.h").write_text("\n".join(h_out) + "\n")
    print(f"{len(names)} glyphs")


if __name__ == "__main__":
    main()
