#!/usr/bin/env python3
"""
Generates the watchface background: a GBA-era Pokemon route field — soft
checkered grass tiles with scattered darker tufts — as an LVGL C array.

Usage: python3 tools/make_field_bg.py app/sprites
"""
import random
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).parent))
from convert_sprites import emit_frame

SCREEN_WIDTH = 410
SCREEN_HEIGHT = 502
PIXEL_SIZE = 6   # matches the pet's default sprite scale so pixel grids agree
TILE = 8         # logical pixels per grass tile

BASE_LIGHT = (136, 200, 120)
BASE_DARK = (122, 186, 106)
TUFT = (74, 140, 74)
TUFT_SHADOW = (98, 164, 90)

TUFT_SHAPE = [(1, 0), (3, 0), (0, 1), (2, 1), (4, 1), (1, 2), (3, 2)]


def main() -> None:
    out_dir = Path(sys.argv[1])
    random.seed(7)

    columns = -(-SCREEN_WIDTH // PIXEL_SIZE)
    rows = -(-SCREEN_HEIGHT // PIXEL_SIZE)
    canvas = Image.new("RGBA", (columns, rows))
    pixels = canvas.load()

    for y in range(rows):
        for x in range(columns):
            checker = (x // TILE + y // TILE) % 2 == 0
            pixels[x, y] = (*(BASE_LIGHT if checker else BASE_DARK), 255)

    for tile_y in range(rows // TILE + 1):
        for tile_x in range(columns // TILE + 1):
            if random.random() > 0.22:
                continue
            origin_x = tile_x * TILE + random.randint(0, 2)
            origin_y = tile_y * TILE + random.randint(0, 3)
            color = TUFT if random.random() < 0.7 else TUFT_SHADOW
            for dx, dy in TUFT_SHAPE:
                x, y = origin_x + dx, origin_y + dy
                if x < columns and y < rows:
                    pixels[x, y] = (*color, 255)

    field = canvas  # native logical pixels; runtime scales by FIELD_BG_SCALE

    c_out = [
        "/* Generated by tools/make_field_bg.py. Do not edit. */",
        '#include "lvgl.h"',
        '#include "field_bg.h"',
        "",
    ]
    emit_frame(c_out, "field_bg_image", field)
    c_out.append("const lv_image_dsc_t *const field_bg = &field_bg_image;")
    c_out.append("")

    h_out = [
        "/* Generated by tools/make_field_bg.py. Do not edit. */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
        f"#define FIELD_BG_SCALE {PIXEL_SIZE}",
        "",
        "extern const lv_image_dsc_t *const field_bg;",
        "",
    ]

    (out_dir / "field_bg.c").write_text("\n".join(c_out) + "\n")
    (out_dir / "field_bg.h").write_text("\n".join(h_out) + "\n")
    print(f"field: {field.width}x{field.height}")


if __name__ == "__main__":
    main()
